module.exports = {
  projects: [
    '<rootDir>/apps/runno',
    '<rootDir>/apps/api',
    '<rootDir>/libs/auth/ui',
    '<rootDir>/libs/activity-types/ui',
    '<rootDir>/libs/activity/ui',
    '<rootDir>/libs/team-settings/ui',
    '<rootDir>/libs/auth/api',
    '<rootDir>/libs/user/api',
    '<rootDir>/libs/shared/grid',
    '<rootDir>/libs/leaderboard/ui',
    '<rootDir>/libs/libs\\activity-types/api',
    '<rootDir>/libs/activity-types/api',
    '<rootDir>/libs/activity/api',
    '<rootDir>/libs/team/api',
    '<rootDir>/libs/team-settings/api',
    '<rootDir>/libs/leaderboard/api',
  ],
};
