import { Component, OnInit } from '@angular/core';
import { Activity } from '@runno/api-interfaces';

@Component({
  selector: 'runno-overview',
  templateUrl: './overview.component.html',
  styleUrls: ['./overview.component.css'],
})
export class OverviewComponent {
  activities: Activity[] = [
    {
      id: 'a',
      userId: 'b',
      type: {
        id: '0',
        title: 'Joggen',
        color: '#000000',
        maxDistancePerDayInKm: 15,
        points: 3,
      },
      distanceInKm: 10,
      timeInMinutes: 30,
      points: 12,
      createdAt: new Date(),
      editedAt: new Date(),
    },
    {
      id: 'a',
      userId: 'b',
      type: {
        id: '0',
        title: 'Joggen',
        color: '#ffffff',
        maxDistancePerDayInKm: 15,
        points: 3,
      },
      distanceInKm: 10,
      timeInMinutes: 30,
      points: 12,
      createdAt: new Date(),
      editedAt: new Date(),
    },
    {
      id: 'a',
      userId: 'b',
      type: {
        id: '0',
        title: 'Joggen',
        color: '#000000',
        maxDistancePerDayInKm: 15,
        points: 3,
      },
      distanceInKm: 10,
      timeInMinutes: 30,
      points: 12,
      createdAt: new Date(),
      editedAt: new Date(),
    },
    {
      id: 'a',
      userId: 'b',
      type: {
        id: '0',
        title: 'Joggen',
        color: '#000000',
        maxDistancePerDayInKm: 15,
        points: 3,
      },
      distanceInKm: 10,
      timeInMinutes: 30,
      points: 12,
      createdAt: new Date(),
      editedAt: new Date(),
    },
    {
      id: 'a',
      userId: 'b',
      type: {
        id: '0',
        title: 'Joggen',
        color: '#000000',
        maxDistancePerDayInKm: 15,
        points: 3,
      },
      distanceInKm: 10,
      timeInMinutes: 30,
      points: 12,
      createdAt: new Date(),
      editedAt: new Date(),
    },
    {
      id: 'a',
      userId: 'b',
      type: {
        id: '0',
        title: 'Joggen',
        color: '#000000',
        maxDistancePerDayInKm: 15,
        points: 3,
      },
      distanceInKm: 10,
      timeInMinutes: 30,
      points: 12,
      createdAt: new Date(),
      editedAt: new Date(),
    },
    {
      id: 'a',
      userId: 'b',
      type: {
        id: '0',
        title: 'Joggen',
        color: '#000000',
        maxDistancePerDayInKm: 15,
        points: 3,
      },
      distanceInKm: 10,
      timeInMinutes: 30,
      points: 12,
      createdAt: new Date(),
      editedAt: new Date(),
    },
    {
      id: 'a',
      userId: 'b',
      type: {
        id: '0',
        title: 'Joggen',
        color: '#000000',
        maxDistancePerDayInKm: 15,
        points: 3,
      },
      distanceInKm: 10,
      timeInMinutes: 30,
      points: 12,
      createdAt: new Date(),
      editedAt: new Date(),
    },
  ];
}
